name: Command Dispatch for testing
on:
  issue_comment:
    types: [created, edited]

jobs:
  command-dispatch-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Build
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.EVENT_PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: run-acceptance-tests
          permission: write
          issue-type: pull-request
          repository: pulumi/eslint-plugin-pulumi
